DROP TABLE IF EXISTS projects;
CREATE TABLE projects (
	id INT(11) AUTO_INCREMENT,
	name VARCHAR(255),
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS types;
CREATE TABLE types (
	id INT(11) AUTO_INCREMENT,
	project_id INT(11),
	name VARCHAR(255),
	
	PRIMARY KEY (id),
	KEY (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS stats;
CREATE TABLE stats (
	id INT(11) AUTO_INCREMENT,
	project_id INT(11),
	type_id INT(11),
	value DECIMAL(10,5),
	created_at TIMESTAMP,
	
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS slices;
CREATE TABLE slices (
	id INT(11) AUTO_INCREMENT,
	stat_id INT(11),
	name VARCHAR(255),
	value DECIMAL(10,5),
	
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

